# This script takes the autogenerated cocktails descriptions and images from  
# cocktail-descriptions.yaml and pastes together one markdown file for each cocktail
# and put those files in the correct place in the Hugo site located in 
# officialcocktails.com

library(tidyverse)
library(yaml)
library(glue)

cocktail_descriptions <- read_yaml("cocktail-descriptions.yaml")

# Clear existing cocktail posts
posts_path <- file.path("officialcocktails.com", "content", "cocktails")
unlink(posts_path, recursive = TRUE)
dir.create(posts_path)

# Moving the images to the right location and compress them at the same time
unlink("officialcocktails.com/static/cocktail-images", recursive = TRUE)
dir.create("officialcocktails.com/static/cocktail-images")
for(source_path in Sys.glob("cocktail-images/*.jpeg")) {
  target_path <- file.path("officialcocktails.com", "static", source_path)
  status <- system2(
    "magick",
    args = c(
      source_path,
      "-resize", "512x512^",
      "-gravity", "center",
      "-extent", "512x512",
      "-quality", "85",
      target_path
    )
  )
  if(status != 0) {
    stop(glue("magick failed for {source_path}"))
  }
}


cocktail_page_template <- r"-(
---
title: "{name}"
draft: false
image: "/{image_path}"
showonlyimage: false
weight: 1
---

{hook}

<!--more-->

**{name} recipe**

{as.yaml(ingredients)}

{method}

![](/{image_path})

{page_body}

)-"

# Compile all the cocktail md files and put them in the correct location
walk(cocktail_descriptions, \(cocktail) {
  print(cocktail$name)
  if(is.null(cocktail$page_body)) {
    cocktail$page_body <- ""
  }
  page <- glue_data(cocktail, cocktail_page_template)
  path <- file.path(posts_path, paste0(cocktail$base_fname, ".md"))
  write_file(page, path)
})

# Render the site, which requires https://gohugo.io/ to be installed
# and opens the site in a browser.
system("cd officialcocktails.com;hugo")
browseURL("http://localhost:1313/")
system("cd officialcocktails.com;hugo server --disableFastRender")
