# This script takes the autogenerated cocktails descriptions and images from  
# cocktail-descriptions.yaml and pastes together one markdown file for each cocktail
# and put those files in the correct place in the Hugo site located in 
# officialcocktails.com

library(tidyverse)
library(yaml)
library(glue)

cocktail_descriptions <- read_yaml("cocktail-descriptions.yaml")

# Clear existing cocktail posts
posts_path <- file.path("officialcocktails.com", "content", "cocktails")
unlink(posts_path, recursive = TRUE)
dir.create(posts_path)

# Moving the images to the right location
unlink("officialcocktails.com/static/cocktail-images", recursive = TRUE)
file.copy("cocktail-images/", "officialcocktails.com/static/", recursive = TRUE)

cocktail_page_template <- r"-(
---
title: "{name}"
draft: false
image: "/{image_path}"
showonlyimage: false
weight: 1
---

{hook}

<!--more-->

**{name} recipe**

{as.yaml(ingredients)}

{method}

![](/{image_path})


## Directions for how to make a {name}

{extended_method}

## Tips for how to make the perfect {name}

{tips}

## Alcohol-free alternative to a {name}

{alcohol_free_alternative}

## {name} fun facts

{fun_facts}

)-"

# Compile all the cocktail md files and put them in the correct location
walk(cocktail_descriptions, \(cocktail) {
  print(cocktail$name)
  page <- glue(cocktail_page_template, .envir = cocktail)
  path <- file.path(posts_path, paste0(cocktail$base_fname, ".md"))
  write_file(page, path)
})

# Render the site, which requires https://gohugo.io/ to be installed
# and opens the site in a browser.
system("cd officialcocktails.com;hugo")
browseURL("http://localhost:1313/")
system("cd officialcocktails.com;hugo server --disableFastRender")

